project:
  type: website
  output-dir: docs
  resources:
    - "project-postcovid.qmd"

website:
  title: "Valeska Kozik"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: skills.qmd
        text: Skills
      - href: participate.qmd
        text: Participate / Teilnahme
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    
